### ISSUE TITLE
Gameplay UI issue *low priority

### ISSUE THREAD

**Issue by ericholsen** [CoraNers/swdv691-ui#12]
On a couple of occassions Done breifly flashed on the screen before the check mark did.  I assume this is just because something runs slow sometimes.  I'm guessing the same thing will happen with "close" showing when the answer is wrong occassionally, although I didn't observe that.  I think just removing the text will fix it.

https://github.com/CoraNers/swdv691-ui/blob/7d3f66156b3bedb390fdbb6dcbcbc7fa87297d5c/src/app/gameplay/gameplay.component.html#L24-L35

**Comment by CoraNers** [comment]
I have investigated this and believe the text that pops up momentarily before showing the icon is alt text for accessibility.  I am only able to reproduce when I throttle down my internet/browser and even then, it's intermittent.  Closing issue.
